pipeline {
    agent any
    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }

    stages {
        stage('Build') {
            steps {
                // Clean before build
                cleanWs()
                // We need to explicitly checkout from SCM here
                checkout scm
                echo "Building ${env.JOB_NAME}..."
            }
        }
        stage('Download Gatling') {
            steps {
                sh 'pwd'
                sh "curl -LO https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.0/gatling-charts-highcharts-bundle-3.9.0-bundle.zip"
            }
        }
        stage('Extract Gatling') {
            steps {
                sh 'unzip -f gatling-charts-highcharts-bundle-3.9.0-bundle.zip'
            }
        }
        stage('Copy script to Gatling') {
            steps {
                sh 'cd /gatling-charts-highcharts-bundle-3.9.0/user-files/simulations'
                sh 'mkdir calculator && rm -r computerdatabase/'
                sh 'cp ../../../CalculatorStressTestSimulation.java .'
            }
        }
    }
}