pipeline {
    agent any
    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Build') {
            steps {
                cleanWs()
                checkout scm
                echo "Building ${env.JOB_NAME}..."
            }
        }
        stage('Download Gatling') {
            steps {
                sh 'pwd'
                sh "curl -LO https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.0/gatling-charts-highcharts-bundle-3.9.0-bundle.zip"
            }
        }
        stage('Extract Gatling') {
            steps {
                sh 'unzip -o /var/jenkins_home/workspace/Calculator-Gatling-Stress-Test/gatling-charts-highcharts-bundle-3.9.0-bundle.zip'
            }
        }
        stage('Copy script to Gatling') {
            steps {
                sh 'pwd'
                sh 'cd gatling-charts-highcharts-bundle-3.9.0/user-files/simulations'
                sh 'mkdir gatling-charts-highcharts-bundle-3.9.0/user-files/simulations/calculator && rm -r gatling-charts-highcharts-bundle-3.9.0/user-files/simulations/computerdatabase'
                sh 'pwd'
                sh 'cp CalculatorStressTestSimulation.java gatling-charts-highcharts-bundle-3.9.0/user-files/simulations/calculator'
            }
        }
        stage('Run Stress Test') {
            steps {
                sh 'gatling-charts-highcharts-bundle-3.9.0/bin/gatling.sh && read -n 1 -r -s -p $'Type the number corresponding to your choice and press enter''
            }
        }
    }
}