pipeline {
    agent any

    stages {
        stage('Download Gatling') {
            steps {
                sh 'pwd'
                sh "curl -LO https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.0/gatling-charts-highcharts-bundle-3.9.0-bundle.zip"
            }
        }
        stage('Extract Gatling') {
            steps {
                sh 'unzip -o /var/jenkins_home/workspace/Calculator-Gatling-Stress-Test/gatling-charts-highcharts-bundle-3.9.0-bundle.zip'
            }
        }
        stage('Copy script to Gatling') {
            steps {
                sh 'pwd'
                sh 'cd gatling-charts-highcharts-bundle-3.9.0/user-files/simulations'
                sh 'pwd'
                sh 'mkdir gatling-charts-highcharts-bundle-3.9.0/user-files/simulations/calculator && rm -r computerdatabase/'
                sh 'cp ../../../CalculatorStressTestSimulation.java .'
            }
        }
    }
}