pipeline {
    agent any
    tools { go 'go-1.20' }
    stages {
        stage('Run Calculator') {
            steps {
                sh 'cd /var/jenkins_home/workspace/Calculator/'
                sh 'chmod +r app && cd app && go build . && go run .'
            }
        }
    }
}