pipeline {
    agent any
    tools { go 'go-1.20' }
    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Build') {
            steps {
                cleanWs()
                checkout scm
                echo "Building ${env.JOB_NAME}..."
            }
        }
        stage('Run Calculator') {
            steps {
                sh 'cd /var/jenkins_home/workspace/Calculator/'
                sh 'chmod +r app && cd app && go build . && go run .'
            }
        }
    }
}